version: "3"

services:
  strapi:
    container_name: strapi-tc1
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT = mongo
      - DATABASE_HOST= loginc.eb6hc30.mongodb.net
      - DATABASE_PORT=27017
      - DATABASE_SSL=true
      - DATABASE_SRV=true
      - DATABASE_NAME = LoginC
      - DATABASE_USERNAME = admin
      - DATABASE_PASSWORD = 1212
    ports:
      - 1337:1337    
   
